### ISSUE TITLE
Create page button is disabled after silverstripe upgrade 4.12 to 4.13.

### ISSUE THREAD

**Issue by hirenatfos** [silverstripe/recipe-cms#74] opened 2023-05-03 08:42 UTC
**Affected Version**
4.13

**Description**
Create page button is disabled after silverstripe upgrade 4.12 to 4.13.

**Steps to Reproduce**

1. login into admin
2. go to pages
3. click on add new button
4. step 1 select page level
5. step 2 select page template
6. noticed create button is disabled.

**Comment by GuySartorelli** [comment] 2023-05-03 22:02
Are you able to reproduce this from a fresh installation of Silverstripe CMS 4.13? I'm not able to reproduce this using the steps you've provided. It seems likely this is related to some customisations in your project.

**Comment by maxime-rainville** [comment] 2023-07-20 04:53
We can't do much with this without more info.

I'll close it for now. If anyone comes across a similar issue, please feel free to open a new issue.

**Closed as completed by maxime-rainville** 2023-07-20 04:53 UTC
Labels: affects/v4, impact/high
